# Generated by Django 3.2 on 2023-08-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('mssg', models.CharField(max_length=100, null=True)),
                ('delete_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
