# Generated by Django 3.2 on 2023-08-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PGRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_name', models.CharField(max_length=50, null=True)),
                ('pg_loaction', models.CharField(max_length=50, null=True)),
                ('pg_type', models.CharField(max_length=50, null=True)),
                ('pg_email', models.EmailField(max_length=50, null=True)),
                ('pg_phone', models.BigIntegerField(null=True)),
                ('room_type', models.CharField(max_length=50, null=True)),
                ('meals', models.CharField(max_length=50, null=True)),
                ('ac_room', models.CharField(max_length=50, null=True)),
                ('laundary', models.CharField(max_length=50, null=True)),
                ('furnish', models.CharField(max_length=50, null=True)),
                ('wifi', models.CharField(max_length=50, null=True)),
                ('m_rent', models.BigIntegerField(null=True)),
                ('s_amount', models.BigIntegerField(null=True)),
                ('a_charge', models.BigIntegerField(null=True)),
                ('o_name', models.CharField(max_length=50, null=True)),
                ('o_phone', models.BigIntegerField(null=True)),
                ('o_address', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('image', models.FileField(null=True, upload_to='media/images/')),
                ('rule', models.FileField(null=True, upload_to='media/images/')),
                ('document', models.FileField(null=True, upload_to='media/images/')),
                ('delete_flag', models.BooleanField(default=False)),
            ],
        ),
    ]
